name: Unit tests and coverage

on:
  push:
  pull_request:
  schedule:
    - cron: "0 4 * * *"

jobs:
  Unit-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10']
        exclude:
          - os: macos-latest
            python-version: '3.7'
          - os: macos-latest
            python-version: '3.8'
          - os: macos-latest
            python-version: '3.9'
          - os: windows-latest
            python-version: '3.7'
          - os: windows-latest
            python-version: '3.8'
          - os: windows-latest
            python-version: '3.9'
      fail-fast: false

    runs-on: ${{ matrix.os }}
    env:
      OS: ${{ matrix.os }}

    steps:
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install tox
        run: pip install tox tox-gh-actions codecov

      - name: Run unit tests
        run: tox

      - name: Upload coverage
        run: codecov

  CLI-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install project
        run: pip install .

      - name: Test transforms CLI tool
        run: tiotr --help

      - name: Test info CLI tool
        run: tiohd --help
