name: Tests

on:
  push:
  pull_request:
  schedule:
    - cron: "0 4 * * *"

jobs:
  Unit-tests:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    env:
      OS: ${{ matrix.os }}

    steps:
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Upgrade pip
        run: pip install --upgrade pip && pip install tox codecov

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Run unit tests
        run: tox -e py

      - name: Upload coverage
        run: codecov

  CLI-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install project
        run: pip install .

      - name: Test transforms CLI tool
        run: tiotr --help

      - name: Test info CLI tool
        run: tiohd --help
