# Tweet the URL of a commit on @TorchIO_commits whenever a push event
# happens on the main branch: https://twitter.com/TorchIO_commits

name: Twitter Push Notification

on:
  push:
    branches:
      - main

jobs:
  Tweet:
    name: Twitter notification
    runs-on: ubuntu-latest
    steps:
      - name: Tweet URL of last commit as @TorchIO_commits
        if: github.repository == 'fepegar/torchio'
        uses: docker://thomasjpfan/twitter-action:0.3
        with:
          args: "-message \"https://github.com/fepegar/torchio/commit/${{ github.sha }}\""
        env:
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
